### ISSUE TITLE
Invoke from the export menu, without local file dialog

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/ion-blender-exporter#2]
Matt asked me to look into ways to open an upload dialog from the File -> Export menu, without causing a file dialog to show up.

I did a little testing, and I was able to get a mostly-blank Blender "Operator" to run there.  By default, most export examples declare a Python class like this:

```
class ExportSomething(bpy.types.Operator, bpy_extras.io_utils.ExportHelper):
```

This is Python's multiple inheritance, and including the `ExportHelper` as a base class is what mandates the file dialog will show up.  But this is not required to install a generic operation into the export menu.  For example:

```
class Export2ion(bpy.types.Operator):
    bl_idname = 'export_scene.cesium_ion'
    bl_label = 'Upload to Cesium ion'
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        # Do something to show the upload UI...
        print("**** Open upload options panel here ****")
        return {'FINISHED'}

# end of class Export2ion

def menu_func_export(self, context):
    self.layout.operator(Export2ion.bl_idname, text='Cesium ion...')

def register():
    bpy.utils.register_class(Export2ion)
    bpy.types.TOPBAR_MT_file_export.append(menu_func_export)

def unregister():
    bpy.utils.unregister_class(Export2ion)
    bpy.types.TOPBAR_MT_file_export.remove(menu_func_export)
```

This doesn't answer the question of how exactly to show the upload UI to the user.  But it allows one to install a menu option in the export list that will invoke arbitrary Python code, without needing to display a file dialog.

@ProjectBarks @mramato

**Comment by ProjectBarks** [comment]
Attempted the following solution but blenders design limits modal usage so we decided against using the file export methodology. See [beta_file_export](https://github.com/AnalyticalGraphicsInc/ion-blender-exporter/tree/beta_file_export) branch for the `file > export` version
